"""Local review gallery: source images, practice status and exact comparisons."""
import html
import json
from pathlib import Path

HERE=Path(__file__).resolve().parent
LIB=HERE.parents[1]/'cover-references/2026-10-07'
manifest=json.loads((LIB/'manifest.json').read_text(encoding='utf-8-sig'))
families={1:'Иллюстрация',2:'Коллаж',3:'Ч/б',4:'Крупный текст',5:'Кино',6:'Крупный текст',7:'Символы',8:'Символы',9:'Ч/б',10:'Крупный текст',11:'Крупный текст',12:'Коллаж',13:'Растр',14:'Доказательство',15:'Ч/б',16:'Ч/б',17:'Гравюра',18:'Карточки',19:'Кино',20:'Схема',21:'Растр',22:'Ч/б',23:'Крупный текст',25:'Доказательство',26:'Схема',27:'Схема',28:'Доказательство',31:'Крупный текст'}
cards=[]
for i in manifest['items']:
    if i['status']!='downloaded': continue
    n=i['input_number']; family=families[n]
    path='../../cover-references/2026-10-07/'+i['path']
    cards.append(f'''<article class="reference" data-family="{family}"><a href="{path}" target="_blank"><img loading="lazy" src="{path}" alt="Reference {n}: {html.escape(i['title'],quote=True)}"></a><div class="meta"><span>{n:02d} · {family}</span><a href="{html.escape(i['source_url'])}" target="_blank" rel="noreferrer">@{html.escape(i['author'])} ↗</a></div><p>{html.escape(i['title'])}</p></article>''')
studies=[('01-monochrome','Ч/б гравюра','Фигура увеличена после проверки в ленте. Без текста.'),('02-editorial','Журнальная иллюстрация','Печать, бумага и отдельная serif-типографика. Исследовательский вариант.'),('03-cinematic','Кинематографический','Исследовательский baseline. Для выбранной текстовой обложки потребуется foreground.'),('04-type','Чистая типографика','Контрольный пример масштаба. Не основной маршрут после уточнения о глубине.'),('05-glass','Крупный текст + реальные знаки','Текущий кандидат v5. Первые версии отклонены; одобрения пока нет.'),('06-system','Схема','Сдержанная альтернатива по референсам 26/27. Нужен явный выбор этого направления.')]
study_html=''.join(f'''<article><a href="final/{slug}.png" target="_blank"><img loading="lazy" src="final/{slug}.png" alt="{title}"></a><div class="meta"><span>{slug[:2]} · {title}</span><a href="final/{slug}.json">JSON ↗</a></div><p>{desc}</p></article>''' for slug,title,desc in studies)
filters=''.join(f'<button data-filter="{f}">{f}</button>' for f in sorted(set(families.values())))
document='''<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Обложки — библиотека и практика</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#eeede9;color:#1b1b1b;font:16px/1.5 system-ui,sans-serif}main{max-width:1500px;margin:auto;padding:48px 32px 80px}header{display:flex;justify-content:space-between;align-items:start;border-bottom:1px solid #c6c5bf;padding-bottom:28px}h1{font-size:clamp(34px,5vw,72px);line-height:1.06;letter-spacing:-.05em;max-width:950px;margin:14px 0 20px;font-weight:750}h2{font-size:30px;letter-spacing:-.03em;margin:56px 0 12px}p{max-width:780px;color:#53534f}a{color:inherit;text-decoration:none}a:hover{text-decoration:underline}nav{display:flex;gap:18px;flex-wrap:wrap;font-size:14px}small,.eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:.13em}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:34px 24px}article{min-width:0}article img{width:100%;aspect-ratio:5/2;object-fit:contain;background:#d9d8d3;display:block}article p{font-size:14px;margin:8px 0 0;line-height:1.4}.meta{display:flex;justify-content:space-between;gap:12px;margin-top:10px;font-size:13px}.meta span{font-weight:650}.meta a{color:#696962}.filters{display:flex;flex-wrap:wrap;gap:8px;margin:20px 0 26px}button{border:1px solid #c7c5bc;border-radius:4px;background:transparent;padding:8px 12px;font:inherit;font-size:13px;cursor:pointer}button.active{color:#fff;background:#222;border-color:#222}.compare{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin:24px 0}.compare img{width:100%;display:block}.compare p{font-size:13px;margin:6px 0}.note{padding:18px 0;border-top:1px solid #c6c5bf;border-bottom:1px solid #c6c5bf;max-width:none}.review{background:#dfded7;padding:24px;margin-top:20px;max-width:950px}.review ol{padding-left:22px}.review li{margin:8px 0}.history{display:flex;gap:16px;flex-wrap:wrap;margin-top:18px;font-size:14px}[hidden]{display:none!important}.thumbs{display:flex;gap:36px;flex-wrap:wrap;margin:24px 0}.thumbs img{width:340px;max-width:100%}footer{margin-top:70px;padding-top:20px;border-top:1px solid #c6c5bf;font-size:13px;color:#666}@media(max-width:700px){main{padding:24px 16px}header{display:block}.grid,.compare{grid-template-columns:1fr}.meta{font-size:12px}h2{margin-top:40px}}
</style><main><header><div><div class="eyebrow">Cover lab · 07.10.2026</div><h1>Стиль начинается<br>с композиции.</h1><p>28 скачанных оригиналов, 12 визуальных направлений и 6 учебных макетов. Текст верстается отдельно. Реальные логотипы сохраняются реальными.</p></div><nav><a href="#revision">Последняя правка</a><a href="#studies">Практика</a><a href="#library">Референсы</a></nav></header>
<section id="revision"><h2>Синий: оригинал и текущая версия</h2><p>v5 — кандидат после двух прямых замечаний Кирилла. Сравнение выполняется после каждой существенной правки. Это не подтверждение качества или эффективности автором.</p><div class="compare"><div><img src="../../cover-references/2026-10-07/originals/06-aleksascales-2088259816296726744.jpg" alt="Оригинал organic playbook"><p>Оригинал · @aleksascales</p></div><div><a href="final/05-glass.png"><img src="final/05-glass.png" alt="Текущая синяя версия v5"></a><p>v5 · близкие строки, реальные знаки, контактные тени</p></div></div><div class="thumbs"><img src="reference-thumb.png" alt="Оригинал 340px"><img src="final/05-glass-thumb.png" alt="Текущая версия 340px"></div><div class="review"><strong>Что изменилось на практике</strong><ol><li>Убран generic play-объект. Знаки TikTok и Instagram вставлены из App Store artwork в отдельно сгенерированные корпуса.</li><li>Собрана иерархия: одно огромное слово, меньшие строки рядом, читаемое перекрытие букв.</li><li>После сравнения исправлены парение иконок и оторванные подписи. Почти прозрачные поля PNG мешали точно поставить контактные тени.</li></ol><p>Материал всё ещё отличается: оригинал более прозрачный и окрашенный, наш вариант — тяжёлое бесцветное стекло с настоящими app tiles. Нельзя считать это точным повтором.</p></div><div class="history"><a href="iterations/05-glass-v1-rejected.png">v1 · отклонён</a><a href="iterations/reference-vs-v3.jpg">v3 · замечание о пропорциях</a><a href="iterations/reference-vs-v4.jpg">v4 · поиск причины парения</a><a href="reference-comparison.jpg">Полный лист сравнения</a><a href="review.md">Журнал решений</a></div></section>
<section id="studies"><h2>Практика: разные задачи, разные стили</h2><p class="note">Учебные темы без выдуманных результатов. Остальные макеты — исследовательские направления; они не объявлены принятыми и не заменяют выбранную пользователем обложку.</p><div class="grid">STUDIES</div></section>
<section id="library"><h2>Оригиналы из твоих ссылок</h2><p>Нажми на изображение для исходного файла. Автор ведёт к исходному посту. Два повтора учтены в manifest; ссылка Jesse ведёт только на профиль.</p><div class="filters"><button class="active" data-filter="all">Все · 28</button>FILTERS</div><div class="grid" id="references">CARDS</div></section>
<footer><a href="../../cover-references/2026-10-07/manifest.json">Manifest: источники, размеры, хеши</a> · <a href="assets/prompts.json">Промпты иллюстраций</a> · <a href="brief.json">Brief и обратная связь</a><p>Локальная учебная библиотека. Чужие обложки сохранены как референсы. Цифры на них — утверждения источников, не результаты Кирилла. Ничего не опубликовано.</p></footer></main><script>document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.reference').forEach(x=>x.hidden=b.dataset.filter!=='all'&&x.dataset.family!==b.dataset.filter)}));</script></html>'''
document=document.replace('STUDIES',study_html).replace('FILTERS',filters).replace('CARDS',''.join(cards))
(HERE/'index.html').write_text(document,encoding='utf-8')
from PIL import Image
ref=Image.open(LIB/'originals/06-aleksascales-2088259816296726744.jpg').convert('RGB')
ref.resize((340,136),Image.Resampling.LANCZOS).save(HERE/'reference-thumb.png')
print(f'Gallery: {len(cards)} references, {len(studies)} studies')
